name: publish
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  publish-image:
    name: release image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        password: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ github.actor }}

    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/kuritka/netutils:latest
        docker push ghcr.io/kuritka/netutils:latest
